# GSE114012 significant differential gene intersection
#
# Read the significant_genes tables generated by 01_limma, calculate the
# intersection among selected analyses, and save the intersected result back
# to each corresponding differential-expression result folder.
#
# Recommended use: modify the configuration below, then run section by section.


# 0. 可修改配置 ---------------------------------------------------------------

DATASET_ID <- "GSE114012"
DATA_TYPE <- "ngs"

TABLE_ROOT <- file.path("results", DATA_TYPE, DATASET_ID, "tables")

# 本次交集分析名称。修改参与分析时，建议同步修改这里，避免输出文件名混淆。
INTERSECTION_NAME <- "LRC_intersection"

# 中央汇总文件。脚本只在这里保存一个summary文件。
SUMMARY_DIR <- file.path(TABLE_ROOT, "intersections", INTERSECTION_NAME)
SUMMARY_FILE <- file.path(
  SUMMARY_DIR,
  paste0(DATASET_ID, "_", INTERSECTION_NAME, "_intersection_summary.csv")
)

# 交集使用的基因ID列和上下调判断列。
GENE_ID_COLUMN <- "Feature_ID"
LOGFC_COLUMN <- "logFC"

# 手动控制哪些分析参与交集。需要排除某一项时，将Use改为FALSE即可。
ANALYSIS_SET <- data.frame(
  Analysis_Name = c("LRC_1", "LRC_2", "LRC_3", "LRC_4", "LRC_5", "LRC_6", "LRC_7"),
  Use = c(FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
  stringsAsFactors = FALSE
)

options(width = 200)


# 1. 查找原始significant_genes结果文件 ----------------------------------------

dir.create(SUMMARY_DIR, recursive = TRUE, showWarnings = FALSE)

significant_files <- list.files(
  TABLE_ROOT,
  pattern = "_significant_genes\\.csv$",
  recursive = TRUE,
  full.names = TRUE
)

# 排除本脚本以前生成的intersect版本，避免重复读入。
significant_files <- significant_files[
  !grepl("_intersect_", basename(significant_files))
]

stopifnot(length(significant_files) > 0)

file_info <- data.frame(
  Analysis_Name = basename(dirname(significant_files)),
  Significant_File = significant_files,
  stringsAsFactors = FALSE
)

file_info <- file_info[order(file_info$Analysis_Name), , drop = FALSE]
rownames(file_info) <- NULL

if (any(duplicated(file_info$Analysis_Name))) {
  duplicated_names <- unique(file_info$Analysis_Name[duplicated(file_info$Analysis_Name)])
  stop("More than one original significant_genes file was found for: ",
       paste(duplicated_names, collapse = ", "))
}


# 2. 选择参与交集的分析 --------------------------------------------------------

stopifnot(all(c("Analysis_Name", "Use") %in% colnames(ANALYSIS_SET)))

selected_analyses <- ANALYSIS_SET$Analysis_Name[ANALYSIS_SET$Use]
selected_analyses <- unique(selected_analyses)

missing_analyses <- setdiff(selected_analyses, file_info$Analysis_Name)
if (length(missing_analyses) > 0) {
  stop("No significant_genes file was found for: ",
       paste(missing_analyses, collapse = ", "))
}

stopifnot(length(selected_analyses) >= 2)

selected_file_info <- file_info[
  match(selected_analyses, file_info$Analysis_Name),
  ,
  drop = FALSE
]

cat("\nSelected analyses: ", paste(selected_analyses, collapse = ", "), "\n", sep = "")


# 3. 读取显著差异基因表 --------------------------------------------------------

get_direction <- function(logfc) {
  ifelse(logfc > 0, "Up", ifelse(logfc < 0, "Down", "No_change"))
}

gene_tables <- vector("list", length(selected_analyses))
names(gene_tables) <- selected_analyses

original_columns <- vector("list", length(selected_analyses))
names(original_columns) <- selected_analyses

for (analysis_name in selected_analyses) {
  gene_file <- selected_file_info$Significant_File[
    selected_file_info$Analysis_Name == analysis_name
  ]

  dat <- read.csv(
    gene_file,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )

  stopifnot(GENE_ID_COLUMN %in% colnames(dat))
  stopifnot(LOGFC_COLUMN %in% colnames(dat))

  original_columns[[analysis_name]] <- colnames(dat)

  dat <- dat[
    !is.na(dat[[GENE_ID_COLUMN]]) & dat[[GENE_ID_COLUMN]] != "",
    ,
    drop = FALSE
  ]

  if (any(duplicated(dat[[GENE_ID_COLUMN]]))) {
    dat <- dat[!duplicated(dat[[GENE_ID_COLUMN]]), , drop = FALSE]
  }

  dat$Direction <- get_direction(dat[[LOGFC_COLUMN]])
  gene_tables[[analysis_name]] <- dat
}


# 4. 输入结果概览 --------------------------------------------------------------

input_summary <- do.call(rbind, lapply(selected_analyses, function(analysis_name) {
  dat <- gene_tables[[analysis_name]]

  data.frame(
    Analysis_Name = analysis_name,
    Total_Significant_Genes = nrow(dat),
    Up = sum(dat$Direction == "Up"),
    Down = sum(dat$Direction == "Down"),
    No_change = sum(dat$Direction == "No_change"),
    stringsAsFactors = FALSE
  )
}))

cat("\nInput significant gene summary:\n")
print(input_summary, row.names = FALSE)


# 5. 计算交集及方向统计 --------------------------------------------------------

gene_id_list <- lapply(gene_tables, function(dat) {
  unique(dat[[GENE_ID_COLUMN]])
})

intersect_gene_ids <- Reduce(intersect, gene_id_list)

if (length(intersect_gene_ids) > 0) {
  direction_matrix <- do.call(cbind, lapply(selected_analyses, function(analysis_name) {
    dat <- gene_tables[[analysis_name]]
    dat$Direction[match(intersect_gene_ids, dat[[GENE_ID_COLUMN]])]
  }))

  colnames(direction_matrix) <- selected_analyses

  common_up <- apply(direction_matrix, 1, function(x) all(x == "Up"))
  common_down <- apply(direction_matrix, 1, function(x) all(x == "Down"))
} else {
  common_up <- logical(0)
  common_down <- logical(0)
}

intersection_overview <- data.frame(
  Intersection_Name = INTERSECTION_NAME,
  Selected_Analyses = paste(selected_analyses, collapse = ";"),
  Number_Of_Analyses = length(selected_analyses),
  Total_Intersected_Genes = length(intersect_gene_ids),
  Common_Up = sum(common_up),
  Common_Down = sum(common_down),
  Mixed_Direction = length(intersect_gene_ids) - sum(common_up) - sum(common_down),
  stringsAsFactors = FALSE
)

cat("\nIntersection summary:\n")
print(intersection_overview, row.names = FALSE)


# 6. 保存每个分析对应的交集版significant_genes结果 ----------------------------

output_summary <- do.call(rbind, lapply(selected_analyses, function(analysis_name) {
  dat <- gene_tables[[analysis_name]]
  source_file <- selected_file_info$Significant_File[
    selected_file_info$Analysis_Name == analysis_name
  ]

  keep_index <- dat[[GENE_ID_COLUMN]] %in% intersect_gene_ids
  intersect_dat <- dat[keep_index, original_columns[[analysis_name]], drop = FALSE]

  intersect_file <- file.path(
    dirname(source_file),
    sub(
      "_significant_genes\\.csv$",
      paste0("_", INTERSECTION_NAME, "_intersect_significant_genes.csv"),
      basename(source_file)
    )
  )

  write.csv(intersect_dat, intersect_file, row.names = FALSE)

  data.frame(
    Analysis_Name = analysis_name,
    Significant_Total = nrow(dat),
    Significant_Up = sum(dat$Direction == "Up"),
    Significant_Down = sum(dat$Direction == "Down"),
    Intersect_Total = nrow(intersect_dat),
    Intersect_Up = sum(dat$Direction[keep_index] == "Up"),
    Intersect_Down = sum(dat$Direction[keep_index] == "Down"),
    Intersect_No_change = sum(dat$Direction[keep_index] == "No_change"),
    Source_File = source_file,
    Intersect_File = intersect_file,
    stringsAsFactors = FALSE
  )
}))


# 7. 保存中央汇总 --------------------------------------------------------------

summary_table <- cbind(
  intersection_overview[
    rep(1, nrow(output_summary)),
    ,
    drop = FALSE
  ],
  output_summary
)

rownames(summary_table) <- NULL

write.csv(summary_table, SUMMARY_FILE, row.names = FALSE)

cat("\nIntersected significant_genes files were saved in each analysis folder.\n")
cat("Summary file: ", SUMMARY_FILE, "\n", sep = "")
cat("\nSignificant gene intersection analysis finished.\n")
