# GSE114012 significant DEG intersection
#
# Read the DEG tables generated by 01_limma, calculate one or more
# significant-gene intersection schemes, and save all outputs in:
# results/ngs/GSE114012/tables/intersect/<intersection_scheme>/
#
# Recommended use: modify section 0, then run this script section by section.


# 0. 可修改配置 ---------------------------------------------------------------

DATASET_ID <- "GSE114012"
DATA_TYPE <- "ngs"

TABLE_ROOT <- file.path("results", DATA_TYPE, DATASET_ID, "tables")
DEG_DIR_NAME <- "DEG"
INTERSECT_DIR_NAME <- "intersect"

INTERSECT_ROOT <- file.path(TABLE_ROOT, INTERSECT_DIR_NAME)

# 交集使用的基因ID列和上下调判断列。
GENE_ID_COLUMN <- "Feature_ID"
LOGFC_COLUMN <- "logFC"

# 交集基因列表保留的注释列；不包含logFC、P值等差异分析统计量。
GENE_ANNOTATION_COLUMNS <- c(
  "Feature_ID", "GeneID", "Symbol", "Ensembl", "Entrez", "Biotype", "Length"
)

# 多套交集方案。
# 新增方案时，只需要按下面格式增加一行；顺序会影响交集基因的输出排序。
INTERSECTION_SCHEMES <- list(
  DLD1_HCT15_SW48 = c("DLD1", "HCT15", "SW48"),
  DLD1_HCT15 = c("DLD1", "HCT15"),
  HT55_SW948 = c("HT55", "SW948"),
  SW948_RKO = c("SW948", "RKO")
)

# 运行哪些交集方案。
# 可设为names(INTERSECTION_SCHEMES)运行全部；也可只写部分方案名。
SCHEMES_TO_RUN <- names(INTERSECTION_SCHEMES)
# SCHEMES_TO_RUN <- c("DLD1_HCT15_SW48")

# 重跑时清空对应交集方案目录，避免旧文件与新结果混在一起。
OVERWRITE_SCHEME_OUTPUT <- TRUE

# 清理旧版脚本生成在tables/<analysis_name>/intersect/下的分散结果。
REMOVE_LEGACY_ANALYSIS_INTERSECT_DIRS <- TRUE

# 交集后的基因在单个差异分析结果中展示。
# TRUE时，DLD1_HCT15_SW48会展开为DLD1、HCT15、SW48，不输出带"_"的组合分析目录。
OUTPUT_SINGLE_ANALYSIS_ONLY <- TRUE

options(width = 200)


# 1. 常用函数 -----------------------------------------------------------------

sanitize_file_name <- function(x) {
  x <- gsub("[^A-Za-z0-9_.-]+", "_", x)
  x <- gsub("_+", "_", x)
  x <- gsub("^_|_$", "", x)
  x
}

get_direction <- function(logfc) {
  ifelse(logfc > 0, "Up", ifelse(logfc < 0, "Down", "No_change"))
}

get_analysis_name_from_deg_file <- function(file_name) {
  basename(dirname(dirname(file_name)))
}

get_deg_file_info <- function(table_root) {
  significant_files <- list.files(
    table_root,
    pattern = "_significant_genes[.]csv$",
    recursive = TRUE,
    full.names = TRUE
  )
  all_genes_files <- list.files(
    table_root,
    pattern = "_all_genes[.]csv$",
    recursive = TRUE,
    full.names = TRUE
  )

  significant_files <- significant_files[
    basename(dirname(significant_files)) == DEG_DIR_NAME
  ]
  all_genes_files <- all_genes_files[
    basename(dirname(all_genes_files)) == DEG_DIR_NAME
  ]

  significant_files <- significant_files[
    !grepl("_intersect_", basename(significant_files))
  ]
  all_genes_files <- all_genes_files[
    !grepl("_intersect_", basename(all_genes_files))
  ]

  stopifnot(length(significant_files) > 0)
  stopifnot(length(all_genes_files) > 0)

  significant_info <- data.frame(
    Analysis_Name = vapply(
      significant_files,
      get_analysis_name_from_deg_file,
      character(1)
    ),
    Significant_File = significant_files,
    stringsAsFactors = FALSE
  )

  all_genes_info <- data.frame(
    Analysis_Name = vapply(
      all_genes_files,
      get_analysis_name_from_deg_file,
      character(1)
    ),
    All_Genes_File = all_genes_files,
    stringsAsFactors = FALSE
  )

  if (any(duplicated(significant_info$Analysis_Name))) {
    duplicated_names <- unique(significant_info$Analysis_Name[
      duplicated(significant_info$Analysis_Name)
    ])
    stop(
      "More than one significant_genes file was found for: ",
      paste(duplicated_names, collapse = ", ")
    )
  }

  if (any(duplicated(all_genes_info$Analysis_Name))) {
    duplicated_names <- unique(all_genes_info$Analysis_Name[
      duplicated(all_genes_info$Analysis_Name)
    ])
    stop(
      "More than one all_genes file was found for: ",
      paste(duplicated_names, collapse = ", ")
    )
  }

  file_info <- merge(
    significant_info,
    all_genes_info,
    by = "Analysis_Name",
    all = FALSE
  )

  file_info <- file_info[order(file_info$Analysis_Name), , drop = FALSE]
  rownames(file_info) <- NULL

  file_info
}

read_deg_table <- function(gene_file) {
  dat <- read.csv(
    gene_file,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )

  stopifnot(GENE_ID_COLUMN %in% colnames(dat))
  stopifnot(LOGFC_COLUMN %in% colnames(dat))

  dat <- dat[
    !is.na(dat[[GENE_ID_COLUMN]]) & dat[[GENE_ID_COLUMN]] != "",
    ,
    drop = FALSE
  ]

  if (any(duplicated(dat[[GENE_ID_COLUMN]]))) {
    dat <- dat[!duplicated(dat[[GENE_ID_COLUMN]]), , drop = FALSE]
  }

  dat$Direction <- get_direction(dat[[LOGFC_COLUMN]])
  dat
}

make_gene_annotation_table <- function(intersect_gene_ids, selected_analyses, significant_tables) {
  first_table <- significant_tables[[selected_analyses[1]]]

  annotation_columns <- intersect(GENE_ANNOTATION_COLUMNS, colnames(first_table))
  annotation_columns <- unique(c(GENE_ID_COLUMN, annotation_columns))

  first_table[
    match(intersect_gene_ids, first_table[[GENE_ID_COLUMN]]),
    annotation_columns,
    drop = FALSE
  ]
}

get_deg_output_analyses <- function(selected_analyses) {
  if (OUTPUT_SINGLE_ANALYSIS_ONLY) {
    selected_analyses <- unlist(strsplit(selected_analyses, "_", fixed = TRUE))
  }

  unique(selected_analyses)
}


# 2. 查找差异分析结果 ----------------------------------------------------------

dir.create(INTERSECT_ROOT, recursive = TRUE, showWarnings = FALSE)

if (REMOVE_LEGACY_ANALYSIS_INTERSECT_DIRS) {
  legacy_intersect_dirs <- file.path(
    list.dirs(TABLE_ROOT, recursive = FALSE, full.names = TRUE),
    INTERSECT_DIR_NAME
  )
  legacy_intersect_dirs <- legacy_intersect_dirs[
    dir.exists(legacy_intersect_dirs)
  ]

  if (length(legacy_intersect_dirs) > 0) {
    unlink(legacy_intersect_dirs, recursive = TRUE)
  }
}

file_info <- get_deg_file_info(TABLE_ROOT)

stopifnot(length(INTERSECTION_SCHEMES) > 0)
stopifnot(!is.null(names(INTERSECTION_SCHEMES)))
stopifnot(!any(names(INTERSECTION_SCHEMES) == ""))
stopifnot(all(SCHEMES_TO_RUN %in% names(INTERSECTION_SCHEMES)))

active_schemes <- INTERSECTION_SCHEMES[SCHEMES_TO_RUN]
intersection_analyses <- unique(unlist(active_schemes))

deg_output_analyses_by_scheme <- lapply(active_schemes, get_deg_output_analyses)
required_analyses <- unique(c(
  intersection_analyses,
  unique(unlist(deg_output_analyses_by_scheme))
))

missing_analyses <- setdiff(required_analyses, file_info$Analysis_Name)
if (length(missing_analyses) > 0) {
  stop(
    "No DEG file was found for: ",
    paste(missing_analyses, collapse = ", ")
  )
}

selected_file_info <- file_info[
  match(required_analyses, file_info$Analysis_Name),
  ,
  drop = FALSE
]


# 3. 读取差异分析结果 ----------------------------------------------------------

significant_tables <- vector("list", length(intersection_analyses))
names(significant_tables) <- intersection_analyses

all_gene_tables <- vector("list", length(required_analyses))
names(all_gene_tables) <- required_analyses

all_gene_columns <- vector("list", length(required_analyses))
names(all_gene_columns) <- required_analyses

for (analysis_name in intersection_analyses) {
  gene_file <- selected_file_info$Significant_File[
    selected_file_info$Analysis_Name == analysis_name
  ]

  significant_tables[[analysis_name]] <- read_deg_table(gene_file)
}

for (analysis_name in required_analyses) {
  gene_file <- selected_file_info$All_Genes_File[
    selected_file_info$Analysis_Name == analysis_name
  ]

  dat <- read_deg_table(gene_file)

  all_gene_tables[[analysis_name]] <- dat
  all_gene_columns[[analysis_name]] <- setdiff(colnames(dat), "Direction")
}


# 4. 输入结果概览 --------------------------------------------------------------

input_summary <- do.call(rbind, lapply(intersection_analyses, function(analysis_name) {
  dat <- significant_tables[[analysis_name]]

  data.frame(
    Analysis_Name = analysis_name,
    Total_Significant_Genes = nrow(dat),
    Up = sum(dat$Direction == "Up"),
    Down = sum(dat$Direction == "Down"),
    No_change = sum(dat$Direction == "No_change"),
    stringsAsFactors = FALSE
  )
}))

cat("\nInput significant gene summary:\n")
print(input_summary, row.names = FALSE)


# 5. 按方案计算交集并保存 ------------------------------------------------------

scheme_summary_list <- vector("list", length(active_schemes))
names(scheme_summary_list) <- names(active_schemes)

output_summary_list <- list()

cat("\nRunning intersection schemes...\n")
progress_bar <- utils::txtProgressBar(
  min = 0,
  max = length(active_schemes),
  style = 3
)

for (scheme_index in seq_along(active_schemes)) {
  intersection_name <- names(active_schemes)[scheme_index]
  selected_analyses <- unique(active_schemes[[scheme_index]])
  deg_output_analyses <- get_deg_output_analyses(selected_analyses)

  stopifnot(length(selected_analyses) >= 2)

  safe_intersection_name <- sanitize_file_name(intersection_name)
  intersection_dir <- file.path(INTERSECT_ROOT, safe_intersection_name)

  if (OVERWRITE_SCHEME_OUTPUT && dir.exists(intersection_dir)) {
    unlink(intersection_dir, recursive = TRUE)
  }
  dir.create(intersection_dir, recursive = TRUE, showWarnings = FALSE)

  gene_id_list <- lapply(selected_analyses, function(analysis_name) {
    significant_tables[[analysis_name]][[GENE_ID_COLUMN]]
  })

  intersect_gene_set <- Reduce(intersect, gene_id_list)
  first_gene_ids <- significant_tables[[selected_analyses[1]]][[GENE_ID_COLUMN]]
  intersect_gene_ids <- first_gene_ids[first_gene_ids %in% intersect_gene_set]

  if (length(intersect_gene_ids) > 0) {
    direction_matrix <- do.call(cbind, lapply(selected_analyses, function(analysis_name) {
      dat <- significant_tables[[analysis_name]]
      dat$Direction[match(intersect_gene_ids, dat[[GENE_ID_COLUMN]])]
    }))
    colnames(direction_matrix) <- selected_analyses

    common_up <- apply(direction_matrix, 1, function(x) all(x == "Up"))
    common_down <- apply(direction_matrix, 1, function(x) all(x == "Down"))
  } else {
    common_up <- logical(0)
    common_down <- logical(0)
  }

  gene_annotation_table <- make_gene_annotation_table(
    intersect_gene_ids = intersect_gene_ids,
    selected_analyses = selected_analyses,
    significant_tables = significant_tables
  )

  gene_list_file <- file.path(
    intersection_dir,
    paste0(DATASET_ID, "_", safe_intersection_name, "_intersect_gene_list.csv")
  )

  write.csv(gene_annotation_table, gene_list_file, row.names = FALSE)

  saved_gene_annotation_table <- read.csv(
    gene_list_file,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
  stopifnot(nrow(saved_gene_annotation_table) == length(intersect_gene_ids))

  scheme_summary <- data.frame(
    Intersection_Name = intersection_name,
    Selected_Analyses = paste(selected_analyses, collapse = ";"),
    DEG_Result_Analyses = paste(deg_output_analyses, collapse = ";"),
    Number_Of_Analyses = length(selected_analyses),
    Total_Intersected_Genes = length(intersect_gene_ids),
    Common_Up = sum(common_up),
    Common_Down = sum(common_down),
    Mixed_Direction = length(intersect_gene_ids) - sum(common_up) - sum(common_down),
    Gene_List_File = gene_list_file,
    stringsAsFactors = FALSE
  )

  scheme_summary_list[[scheme_index]] <- scheme_summary

  for (analysis_name in deg_output_analyses) {
    dat <- all_gene_tables[[analysis_name]]
    source_file <- selected_file_info$All_Genes_File[
      selected_file_info$Analysis_Name == analysis_name
    ]

    match_index <- match(intersect_gene_ids, dat[[GENE_ID_COLUMN]])
    stopifnot(!any(is.na(match_index)))

    intersect_deg <- dat[
      match_index,
      all_gene_columns[[analysis_name]],
      drop = FALSE
    ]

    output_metadata <- data.frame(
      Intersection_Name = rep(intersection_name, length(intersect_gene_ids)),
      Intersected_Analyses = rep(paste(selected_analyses, collapse = ";"), length(intersect_gene_ids)),
      DEG_Analysis_Name = rep(analysis_name, length(intersect_gene_ids)),
      Used_In_Intersection = rep(analysis_name %in% selected_analyses, length(intersect_gene_ids)),
      DEG_Direction = dat$Direction[match_index],
      stringsAsFactors = FALSE
    )

    intersect_deg <- cbind(output_metadata, intersect_deg)

    analysis_output_dir <- file.path(intersection_dir, sanitize_file_name(analysis_name))
    dir.create(analysis_output_dir, recursive = TRUE, showWarnings = FALSE)

    deg_output_file <- file.path(
      analysis_output_dir,
      paste0(
        DATASET_ID, "_", safe_intersection_name, "_",
        sanitize_file_name(analysis_name), "_intersect_DEG_results.csv"
      )
    )

    write.csv(intersect_deg, deg_output_file, row.names = FALSE)

    saved_intersect_deg <- read.csv(
      deg_output_file,
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
    stopifnot(nrow(saved_intersect_deg) == length(intersect_gene_ids))

    output_summary_list[[length(output_summary_list) + 1]] <- data.frame(
      scheme_summary[
        ,
        c(
          "Intersection_Name", "Selected_Analyses", "Number_Of_Analyses",
          "Total_Intersected_Genes", "Common_Up", "Common_Down",
          "Mixed_Direction", "Gene_List_File"
        ),
        drop = FALSE
      ],
      DEG_Analysis_Name = analysis_name,
      Used_In_Intersection = analysis_name %in% selected_analyses,
      DEG_Output_Rows = nrow(intersect_deg),
      DEG_Output_Up = sum(dat$Direction[match_index] == "Up"),
      DEG_Output_Down = sum(dat$Direction[match_index] == "Down"),
      DEG_Output_No_change = sum(dat$Direction[match_index] == "No_change"),
      DEG_Source_File = source_file,
      DEG_Output_File = deg_output_file,
      stringsAsFactors = FALSE
    )
  }

  scheme_output_summary <- do.call(rbind, output_summary_list)
  scheme_output_summary <- scheme_output_summary[
    scheme_output_summary$Intersection_Name == intersection_name,
    ,
    drop = FALSE
  ]

  scheme_summary_file <- file.path(
    intersection_dir,
    paste0(DATASET_ID, "_", safe_intersection_name, "_intersection_summary.csv")
  )

  write.csv(scheme_output_summary, scheme_summary_file, row.names = FALSE)

  saved_scheme_summary <- read.csv(
    scheme_summary_file,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
  stopifnot(nrow(saved_scheme_summary) == length(deg_output_analyses))
  stopifnot(all(saved_scheme_summary$Total_Intersected_Genes == length(intersect_gene_ids)))
  stopifnot(all(saved_scheme_summary$DEG_Output_Rows == length(intersect_gene_ids)))

  utils::setTxtProgressBar(progress_bar, scheme_index)
}

close(progress_bar)


# 6. 终端快速汇总 --------------------------------------------------------------

scheme_summary_table <- do.call(rbind, scheme_summary_list)
output_summary_table <- do.call(rbind, output_summary_list)

cat("\nIntersection scheme summary:\n")
print(
  scheme_summary_table[
    ,
    c(
      "Intersection_Name", "Number_Of_Analyses",
      "Total_Intersected_Genes", "Common_Up", "Common_Down",
      "Mixed_Direction", "Selected_Analyses"
    )
  ],
  row.names = FALSE
)

cat("\nDEG output summary by analysis:\n")
print(
  output_summary_table[
    ,
    c(
      "Intersection_Name", "DEG_Analysis_Name", "Used_In_Intersection",
      "DEG_Output_Rows", "DEG_Output_Up", "DEG_Output_Down",
      "DEG_Output_No_change"
    )
  ],
  row.names = FALSE
)

cat("\nIntersected gene lists and DEG tables were saved in:\n")
cat(file.path(INTERSECT_ROOT, "<INTERSECTION_SCHEME>"), "\n", sep = "")
cat("\nSignificant DEG intersection analysis finished.\n")
