# GSE114012 significant DEG intersection
#
# Read the significant_genes tables generated by 01_limma, calculate one or
# more intersection schemes, and save intersected DEG tables in:
# results/ngs/GSE114012/tables/<analysis_name>/intersect/
#
# Recommended use: modify section 0, then run this script section by section.


# 0. 可修改配置 ---------------------------------------------------------------

DATASET_ID <- "GSE114012"
DATA_TYPE <- "ngs"

TABLE_ROOT <- file.path("results", DATA_TYPE, DATASET_ID, "tables")
DEG_DIR_NAME <- "DEG"
INTERSECT_DIR_NAME <- "intersect"

# 交集使用的基因ID列和上下调判断列。
GENE_ID_COLUMN <- "Feature_ID"
LOGFC_COLUMN <- "logFC"

# 输出交集结果时，保留在最前面的基因注释列。
GENE_ANNOTATION_COLUMNS <- c(
  "Feature_ID", "GeneID", "Symbol", "Ensembl", "Entrez", "Biotype", "Length"
)

# 用于横向展示不同差异分析结果的核心列。
DEG_COMPARISON_COLUMNS <- c(
  "Direction", "logFC", "P.Value", "adj.P.Val", "AveExpr", "t", "B"
)

# 多套交集方案。
# 新增方案时，只需要按下面格式增加一行；顺序会影响交集基因的输出排序。
INTERSECTION_SCHEMES <- list(
  DLD1_HCT15_SW48 = c("DLD1", "HCT15", "SW48"),
  DLD1_HCT15 = c("DLD1", "HCT15"),
  HT55_SW948 = c("HT55", "SW948"),
  SW948_RKO = c("SW948", "RKO")
)

# 运行哪些交集方案。
# 可设为names(INTERSECTION_SCHEMES)运行全部；也可只写部分方案名。
SCHEMES_TO_RUN <- names(INTERSECTION_SCHEMES)
# SCHEMES_TO_RUN <- c("CRC_LRC_core")

options(width = 200)


# 1. 常用函数 -----------------------------------------------------------------

sanitize_file_name <- function(x) {
  x <- gsub("[^A-Za-z0-9_.-]+", "_", x)
  x <- gsub("_+", "_", x)
  x <- gsub("^_|_$", "", x)
  x
}

get_direction <- function(logfc) {
  ifelse(logfc > 0, "Up", ifelse(logfc < 0, "Down", "No_change"))
}

find_significant_files <- function(table_root) {
  significant_files <- list.files(
    table_root,
    pattern = "_significant_genes[.]csv$",
    recursive = TRUE,
    full.names = TRUE
  )

  significant_files <- significant_files[
    basename(dirname(significant_files)) == DEG_DIR_NAME
  ]
  significant_files <- significant_files[
    !grepl("_intersect_", basename(significant_files))
  ]

  stopifnot(length(significant_files) > 0)

  file_info <- data.frame(
    Analysis_Name = basename(dirname(dirname(significant_files))),
    Significant_File = significant_files,
    stringsAsFactors = FALSE
  )

  file_info <- file_info[order(file_info$Analysis_Name), , drop = FALSE]
  rownames(file_info) <- NULL

  if (any(duplicated(file_info$Analysis_Name))) {
    duplicated_names <- unique(file_info$Analysis_Name[duplicated(file_info$Analysis_Name)])
    stop(
      "More than one original significant_genes file was found for: ",
      paste(duplicated_names, collapse = ", ")
    )
  }

  file_info
}

read_significant_table <- function(gene_file) {
  dat <- read.csv(
    gene_file,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )

  stopifnot(GENE_ID_COLUMN %in% colnames(dat))
  stopifnot(LOGFC_COLUMN %in% colnames(dat))

  dat <- dat[
    !is.na(dat[[GENE_ID_COLUMN]]) & dat[[GENE_ID_COLUMN]] != "",
    ,
    drop = FALSE
  ]

  if (any(duplicated(dat[[GENE_ID_COLUMN]]))) {
    dat <- dat[!duplicated(dat[[GENE_ID_COLUMN]]), , drop = FALSE]
  }

  dat$Direction <- get_direction(dat[[LOGFC_COLUMN]])
  dat
}

make_comparison_table <- function(intersect_gene_ids, selected_analyses, gene_tables) {
  first_table <- gene_tables[[selected_analyses[1]]]

  annotation_columns <- intersect(GENE_ANNOTATION_COLUMNS, colnames(first_table))
  annotation_columns <- unique(c(GENE_ID_COLUMN, annotation_columns))

  comparison_table <- first_table[
    match(intersect_gene_ids, first_table[[GENE_ID_COLUMN]]),
    annotation_columns,
    drop = FALSE
  ]

  for (analysis_name in selected_analyses) {
    dat <- gene_tables[[analysis_name]]
    dat <- dat[
      match(intersect_gene_ids, dat[[GENE_ID_COLUMN]]),
      ,
      drop = FALSE
    ]

    comparison_columns <- intersect(DEG_COMPARISON_COLUMNS, colnames(dat))
    comparison_block <- dat[, comparison_columns, drop = FALSE]

    colnames(comparison_block) <- paste(
      sanitize_file_name(analysis_name),
      comparison_columns,
      sep = "_"
    )

    comparison_table <- cbind(comparison_table, comparison_block)
  }

  comparison_table
}


# 2. 查找差异分析结果 ----------------------------------------------------------

file_info <- find_significant_files(TABLE_ROOT)

stopifnot(length(INTERSECTION_SCHEMES) > 0)
stopifnot(!is.null(names(INTERSECTION_SCHEMES)))
stopifnot(!any(names(INTERSECTION_SCHEMES) == ""))
stopifnot(all(SCHEMES_TO_RUN %in% names(INTERSECTION_SCHEMES)))

active_schemes <- INTERSECTION_SCHEMES[SCHEMES_TO_RUN]
required_analyses <- unique(unlist(active_schemes))

missing_analyses <- setdiff(required_analyses, file_info$Analysis_Name)
if (length(missing_analyses) > 0) {
  stop(
    "No significant_genes file was found for: ",
    paste(missing_analyses, collapse = ", ")
  )
}

selected_file_info <- file_info[
  match(required_analyses, file_info$Analysis_Name),
  ,
  drop = FALSE
]


# 3. 读取显著差异基因表 --------------------------------------------------------

gene_tables <- vector("list", length(required_analyses))
names(gene_tables) <- required_analyses

original_columns <- vector("list", length(required_analyses))
names(original_columns) <- required_analyses

for (analysis_name in required_analyses) {
  gene_file <- selected_file_info$Significant_File[
    selected_file_info$Analysis_Name == analysis_name
  ]

  dat <- read_significant_table(gene_file)

  gene_tables[[analysis_name]] <- dat
  original_columns[[analysis_name]] <- setdiff(colnames(dat), "Direction")
}


# 4. 输入结果概览 --------------------------------------------------------------

input_summary <- do.call(rbind, lapply(required_analyses, function(analysis_name) {
  dat <- gene_tables[[analysis_name]]

  data.frame(
    Analysis_Name = analysis_name,
    Total_Significant_Genes = nrow(dat),
    Up = sum(dat$Direction == "Up"),
    Down = sum(dat$Direction == "Down"),
    No_change = sum(dat$Direction == "No_change"),
    stringsAsFactors = FALSE
  )
}))

cat("\nInput significant gene summary:\n")
print(input_summary, row.names = FALSE)


# 5. 按方案计算交集并保存 ------------------------------------------------------

scheme_summary_list <- vector("list", length(active_schemes))
names(scheme_summary_list) <- names(active_schemes)

output_summary_list <- list()

cat("\nRunning intersection schemes...\n")
progress_bar <- utils::txtProgressBar(
  min = 0,
  max = length(active_schemes),
  style = 3
)

for (scheme_index in seq_along(active_schemes)) {
  intersection_name <- names(active_schemes)[scheme_index]
  selected_analyses <- unique(active_schemes[[scheme_index]])

  stopifnot(length(selected_analyses) >= 2)

  gene_id_list <- lapply(selected_analyses, function(analysis_name) {
    gene_tables[[analysis_name]][[GENE_ID_COLUMN]]
  })

  intersect_gene_set <- Reduce(intersect, gene_id_list)
  first_gene_ids <- gene_tables[[selected_analyses[1]]][[GENE_ID_COLUMN]]
  intersect_gene_ids <- first_gene_ids[first_gene_ids %in% intersect_gene_set]

  if (length(intersect_gene_ids) > 0) {
    direction_matrix <- do.call(cbind, lapply(selected_analyses, function(analysis_name) {
      dat <- gene_tables[[analysis_name]]
      dat$Direction[match(intersect_gene_ids, dat[[GENE_ID_COLUMN]])]
    }))
    colnames(direction_matrix) <- selected_analyses

    common_up <- apply(direction_matrix, 1, function(x) all(x == "Up"))
    common_down <- apply(direction_matrix, 1, function(x) all(x == "Down"))
  } else {
    common_up <- logical(0)
    common_down <- logical(0)
  }

  direction_class <- rep("Mixed_Direction", length(intersect_gene_ids))
  direction_class[common_up] <- "Common_Up"
  direction_class[common_down] <- "Common_Down"

  comparison_table <- make_comparison_table(
    intersect_gene_ids = intersect_gene_ids,
    selected_analyses = selected_analyses,
    gene_tables = gene_tables
  )

  scheme_summary <- data.frame(
    Intersection_Name = intersection_name,
    Selected_Analyses = paste(selected_analyses, collapse = ";"),
    Number_Of_Analyses = length(selected_analyses),
    Total_Intersected_Genes = length(intersect_gene_ids),
    Common_Up = sum(common_up),
    Common_Down = sum(common_down),
    Mixed_Direction = length(intersect_gene_ids) - sum(common_up) - sum(common_down),
    stringsAsFactors = FALSE
  )

  scheme_summary_list[[scheme_index]] <- scheme_summary

  comparison_columns <- setdiff(colnames(comparison_table), GENE_ANNOTATION_COLUMNS)
  safe_intersection_name <- sanitize_file_name(intersection_name)

  for (analysis_name in selected_analyses) {
    dat <- gene_tables[[analysis_name]]
    source_file <- selected_file_info$Significant_File[
      selected_file_info$Analysis_Name == analysis_name
    ]

    match_index <- match(intersect_gene_ids, dat[[GENE_ID_COLUMN]])
    intersect_dat <- dat[
      match_index,
      original_columns[[analysis_name]],
      drop = FALSE
    ]

    output_metadata <- data.frame(
      Intersection_Name = rep(intersection_name, length(intersect_gene_ids)),
      Intersected_Analyses = rep(paste(selected_analyses, collapse = ";"), length(intersect_gene_ids)),
      Direction_Class = direction_class,
      Analysis_Name = rep(analysis_name, length(intersect_gene_ids)),
      Analysis_Direction = dat$Direction[match_index],
      stringsAsFactors = FALSE
    )

    intersect_dat <- cbind(
      output_metadata,
      intersect_dat,
      comparison_table[, comparison_columns, drop = FALSE]
    )

    output_dir <- file.path(TABLE_ROOT, analysis_name, INTERSECT_DIR_NAME)
    dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

    safe_analysis_name <- sanitize_file_name(analysis_name)

    intersect_file <- file.path(
      output_dir,
      paste0(
        DATASET_ID, "_", safe_analysis_name, "_",
        safe_intersection_name, "_intersect_significant_genes.csv"
      )
    )

    summary_file <- file.path(
      output_dir,
      paste0(
        DATASET_ID, "_", safe_analysis_name, "_",
        safe_intersection_name, "_intersection_summary.csv"
      )
    )

    output_summary <- data.frame(
      scheme_summary,
      Analysis_Name = analysis_name,
      Significant_Total = nrow(dat),
      Significant_Up = sum(dat$Direction == "Up"),
      Significant_Down = sum(dat$Direction == "Down"),
      Intersect_Total = nrow(intersect_dat),
      Intersect_Up = sum(dat$Direction[match_index] == "Up"),
      Intersect_Down = sum(dat$Direction[match_index] == "Down"),
      Intersect_No_change = sum(dat$Direction[match_index] == "No_change"),
      Source_File = source_file,
      Intersect_File = intersect_file,
      stringsAsFactors = FALSE
    )

    write.csv(intersect_dat, intersect_file, row.names = FALSE)
    write.csv(output_summary, summary_file, row.names = FALSE)

    saved_intersect_dat <- read.csv(
      intersect_file,
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
    saved_summary <- read.csv(
      summary_file,
      stringsAsFactors = FALSE,
      check.names = FALSE
    )

    stopifnot(nrow(saved_intersect_dat) == length(intersect_gene_ids))
    stopifnot(nrow(saved_summary) == 1)
    stopifnot(saved_summary$Intersect_Total == length(intersect_gene_ids))
    stopifnot(saved_summary$Intersect_Up + saved_summary$Intersect_Down +
                saved_summary$Intersect_No_change == saved_summary$Intersect_Total)

    output_summary_list[[length(output_summary_list) + 1]] <- output_summary
  }

  utils::setTxtProgressBar(progress_bar, scheme_index)
}

close(progress_bar)


# 6. 终端快速汇总 --------------------------------------------------------------

scheme_summary_table <- do.call(rbind, scheme_summary_list)
output_summary_table <- do.call(rbind, output_summary_list)

cat("\nIntersection scheme summary:\n")
print(
  scheme_summary_table[
    ,
    c(
      "Intersection_Name", "Number_Of_Analyses",
      "Total_Intersected_Genes", "Common_Up", "Common_Down",
      "Mixed_Direction", "Selected_Analyses"
    )
  ],
  row.names = FALSE
)

cat("\nOutput summary by analysis:\n")
print(
  output_summary_table[
    ,
    c(
      "Intersection_Name", "Analysis_Name", "Significant_Total",
      "Intersect_Total", "Intersect_Up", "Intersect_Down",
      "Intersect_No_change"
    )
  ],
  row.names = FALSE
)

cat("\nIntersected DEG tables were saved in:\n")
cat(file.path(TABLE_ROOT, "<analysis_name>", INTERSECT_DIR_NAME), "\n", sep = "")
cat("\nSignificant DEG intersection analysis finished.\n")
